/*
 * Copyright (c) 2026. gitoido-mc
 * This Source Code Form is subject to the terms of the GNU General Public License v3.0.
 * If a copy of the GNU General Public License v3.0 was not distributed with this file,
 * you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
 */

package lol.gito.radgyms.fabric.datagen.provider.caches

import lol.gito.radgyms.common.CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
import lol.gito.radgyms.common.CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
import lol.gito.radgyms.common.CACHE_DEFAULT_ENTRY_WEIGHT_RARE
import lol.gito.radgyms.common.CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
import lol.gito.radgyms.common.cache.CacheDTO
import net.minecraft.world.item.Rarity

val BUG_CACHE =
    CacheDTO(
        mapOf(
            Rarity.COMMON.serializedName.lowercase() to
                mapOf(
                    "blipbug" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "snom" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "kricketot" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "caterpie" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "weedle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "wurmple" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "scatterbug" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "cascoon" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "kakuna" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "metapod" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "silcoon" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "nymble" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "tarountula" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "spewpa" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "burmy bagworm_cloak=plant" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "burmy bagworm_cloak=sandy" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "burmy bagworm_cloak=trash" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "wimpod" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "shedinja" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "combee" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "spinarak" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "venipede" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "ledyba" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "nincada" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "dewpider" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "surskit" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "rellor" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "paras" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "pineco" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                ),
            Rarity.UNCOMMON.serializedName.lowercase() to
                mapOf(
                    "grubbin" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "cutiefly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "shelmet" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "sizzlipede" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "venonat" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "sewaddle" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "karrablast" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "joltik" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "dwebble" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "skorupi" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "dottler" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "anorith" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "larvesta" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "whirlipede" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "swadloon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "kricketune" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "dustox" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "ledian" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "yanma" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "beautifly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "beedrill" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "butterfree" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                ),
            Rarity.RARE.serializedName.lowercase() to
                mapOf(
                    "ariados" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "charjabug" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "spidops" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "parasect" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=archipelago" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=continental" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=elegant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=fancy" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=forsaken" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=garden" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=high-plains" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=icy-snow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=inferno" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=jungle" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=marine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=meadow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=modern" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=moonsoon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=ocean" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=poke-ball" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=polar" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=river" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=sandstorm" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=savanna" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=sun" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=tundra" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vivillon vivillon_wings=void" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "mothim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "wormadam bagworm_cloak=plant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "wormadam bagworm_cloak=sandy" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "wormadam bagworm_cloak=trash" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "illumise" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "volbeat" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "lokix" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "venomoth" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "araquanid" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "masquerain" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "ninjask" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "ribombee" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "forretress" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "rabsca" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "galvantula" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "vespiqueen" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "frosmoth" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "durant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "crustle" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "scolipede" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "accelgor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "armaldo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "escavalier" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                ),
            Rarity.EPIC.serializedName.lowercase() to
                mapOf(
                    "heracross" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "kleavor" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "leavanny" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "pinsir" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "scizor" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "scyther" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "vikavolt" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "orbeetle" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "shuckle" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "yanmega" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "centiscorch" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "golisopod" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "volcarona" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "buzzwole" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "pheromosa" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "slitherwing" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "genesect" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "genesect techno_drive=water" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "genesect techno_drive=electric" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "genesect techno_drive=fire" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "genesect techno_drive=ice" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "arceus multitype=bug" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "silvally rks_memory=bug" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                ),
        ),
    )
