/*
 * Copyright (c) 2026. gitoido-mc
 * This Source Code Form is subject to the terms of the GNU General Public License v3.0.
 * If a copy of the GNU General Public License v3.0 was not distributed with this file,
 * you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
 */

package lol.gito.radgyms.fabric.datagen.provider.caches

import lol.gito.radgyms.common.*
import lol.gito.radgyms.common.cache.CacheDTO
import net.minecraft.world.item.Rarity

val GRASS_CACHE = CacheDTO(
    mapOf(
        Rarity.COMMON.serializedName.lowercase() to mapOf(
            "applin" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "bounsweet" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "bramblin" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "budew" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "cherubi" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "cottonee" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "electrode hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "fomantis" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "foongus" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "gossifleur" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "hoppip" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "morelull" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "petilil region_bias=hisui" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "petilil" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "seedot" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "shroomish" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "smoliv" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "steenee" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "sunkern" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
            "voltorb hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
        ),
        Rarity.UNCOMMON.serializedName.lowercase() to mapOf(
            "bellsprout" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "cacnea" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "capsakid" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "deerling season=autumn" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "deerling season=summer" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "deerling season=winter" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "dolliv" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "exeggcute" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "ferroseed" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "gloom" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "nuzleaf" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "oddish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "pansage" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "poltchageist" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "pumpkaboo pumpkin_size=large" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "pumpkaboo pumpkin_size=small" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "pumpkaboo pumpkin_size=super" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "roselia" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "shiinotic" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "skiddo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "skiploom" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "snover" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "sunflora" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "tangela" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
            "weepinbell" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
        ),
        Rarity.RARE.serializedName.lowercase() to mapOf(
            "abomasnow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "amoonguss" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "appletun" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "arboliva" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "bellossom" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "brambleghast" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "breloom" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "bulbasaur" to CACHE_STARTER_ENTRY_WEIGHT,
            "cacturne" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "carnivine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "cherrim blossom_form=sunshine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "cherrim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "chespin" to CACHE_STARTER_ENTRY_WEIGHT,
            "chikorita" to CACHE_STARTER_ENTRY_WEIGHT,
            "dipplin" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "eldegoss" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "exeggutor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "ferrothorn" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "flapple" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "gogoat" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "gourgeist pumpkin_size=large" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "gourgeist pumpkin_size=small" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "gourgeist pumpkin_size=super" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "grookey" to CACHE_STARTER_ENTRY_WEIGHT,
            "hydrapple" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "jumpluff" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "kartana" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "leafeon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "lilligant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "lurantis" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "maractus" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "roserade" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "rotom appliance=mow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "rowlet" to CACHE_STARTER_ENTRY_WEIGHT,
            "sawsbuck season=autumn" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "sawsbuck season=summer" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "sawsbuck season=winter" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "scovillain" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "shiftry" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "simisage" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "sinistcha" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "snivy" to CACHE_STARTER_ENTRY_WEIGHT,
            "sprigatito" to CACHE_STARTER_ENTRY_WEIGHT,
            "tangrowth" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "treecko" to CACHE_STARTER_ENTRY_WEIGHT,
            "tropius" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "tsareena" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "turtwig" to CACHE_STARTER_ENTRY_WEIGHT,
            "victreebel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "vileplume" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            "whimsicott" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
        ),
        Rarity.EPIC.serializedName.lowercase() to mapOf(
            "arceus multitype=grass" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "brutebonnet" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "ironleaves" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "ogerpon embody_aspect ogre_mask=teal" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "ogerpon ogre_mask=teal" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "shaymin" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "silvally rks_memory=grass" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "tapubulu" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "virizion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
            "zarude rogue_cape=dada" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
        ),
    )
)
