/*
 * Copyright (c) 2026. gitoido-mc
 * This Source Code Form is subject to the terms of the GNU General Public License v3.0.
 * If a copy of the GNU General Public License v3.0 was not distributed with this file,
 * you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
 */

package lol.gito.radgyms.fabric.datagen.provider.caches

import lol.gito.radgyms.common.*
import lol.gito.radgyms.common.cache.CacheDTO
import net.minecraft.world.item.Rarity

val WATER_CACHE =
    CacheDTO(
        mapOf(
            Rarity.COMMON.serializedName.lowercase() to
                mapOf(
                    "arrokuda" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "barboach" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "basculin fish_stripes=blue" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "basculin fish_stripes=red" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "basculin fish_stripes=white" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "chewtle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "dewpider" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "feebas" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "horsea" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "lotad" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "magikarp" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "mantyke" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "marill" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "tympole" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "wiglett" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "wingull" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "wishiwashi" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "wooper" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                ),
            Rarity.UNCOMMON.serializedName.lowercase() to
                mapOf(
                    "azumarill" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "buizel" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "carvanha" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "castform forecast_form=rainy" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "chinchou" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "clamperl" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "clauncher" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "corphish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "corsola" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "dewott" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "ducklett" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "finizen" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "finneon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "frillish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "goldeen" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "krabby" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "lombre" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "luvdisc" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "oshawott" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "palpitoad" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "panpour" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "pelipper" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "poliwag" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "poliwhirl" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "psyduck" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "pyukumuku" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "quagsire" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "qwilfish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "remoraid" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "seadra" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "seel" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "shellder" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "shellos sea=east" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "shellos sea=west" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "slowpoke" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "staryu" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "tentacool" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "tirtouga" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "wailmer" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "wugtrio" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                ),
            Rarity.RARE.serializedName.lowercase() to
                mapOf(
                    "alomomola" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "araquanid" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "arctovish" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "barraskewda" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "basculegion" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "bruxish" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "carracosta" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "clawitzer" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "cloyster" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "cramorant missile_form=gorging" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "cramorant missile_form=gulping" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "crawdaunt" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "dewgong" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "dondozo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "dracovish" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "drednaw" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "floatzel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "froakie" to CACHE_STARTER_ENTRY_WEIGHT,
                    "gastrodon sea=west" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "golduck" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "gorebyss" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "gyarados" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "huntail" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "jellicent" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "kingdra" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "kingler" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "lanturn" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "lapras" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "ludicolo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "lumineon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "mantine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "milotic" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "mudkip" to CACHE_STARTER_ENTRY_WEIGHT,
                    "octillery" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "oshawott aspect=region-bias-hisui" to CACHE_STARTER_ENTRY_WEIGHT,
                    "palafin" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "piplup" to CACHE_STARTER_ENTRY_WEIGHT,
                    "politoed" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "poliwrath" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "popplio" to CACHE_STARTER_ENTRY_WEIGHT,
                    "quaxly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "relicanth" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "rotom aspect=wash-appliance" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "seaking" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "seismitoad" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "sharpedo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "simipour" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "slowbro" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "slowking" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "sobble" to CACHE_STARTER_ENTRY_WEIGHT,
                    "squirtle" to CACHE_STARTER_ENTRY_WEIGHT,
                    "starmie" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "swanna" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "tatsugiri tatsugiri_texture=curly" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "tatsugiri tatsugiri_texture=droopy" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "tatsugiri tatsugiri_texture=stretchy" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "tentacruel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "totodile" to CACHE_STARTER_ENTRY_WEIGHT,
                    "vaporeon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "veluza" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "wailord" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "whiscash" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                ),
            Rarity.EPIC.serializedName.lowercase() to
                mapOf(
                    "arceus multitype=water" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "keldeo" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "kyogre reversion_state=primal" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "kyogre" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "manaphy" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "ogerpon embody_aspect ogre_mask=wellspring" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "ogerpon ogre_mask=wellspring" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "palafin dolphin_form=hero" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "palkia" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "phione" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "silvally rks_memory=water" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "suicune" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "tapufini" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "urshifu wushu_style=rapid_strike" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "walkingwake" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "wishiwashi schooling_form=school" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                ),
        ),
    )
