#
# Copyright (c) 2025-2026. gitoido-mc
# This Source Code Form is subject to the terms of the GNU General Public License v3.0.
# If a copy of the GNU General Public License v3.0 was not distributed with this file,
# you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
#
org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=true

# Mod Properties
group=lol.gito.radgyms

mod_id=rad_gyms
mod_name=Rad Gyms
mod_author=Gito
mod_issues=
mod_source=
license=GNU GPLv3
credits=
description=Roguelike datapackable gyms in Cobblemon!


# Platform dependencies
minecraft_version=1.21.1
architectury_api_version=13.0.8
neoforge_version=21.1.182
fabric_loader_version=0.18.4
fabric_version=0.116.7+1.21.1

# Kotlin dependencies
fabric_kotlin_version=1.13.12+kotlin.2.4.0
kotlin_for_forge_version=5.11.0

# Cobblemon
use_cobbled_snapshot=false
cobblemon_version=1.7.3
cobblemon_snapshot_version=1.8.0

# Mod dependencies
structure_placer_api_neoforge_version=j18R83Er
structure_placer_api_fabric_version=Tl86aiIE
rctapi_min_version=0.14.6-beta
rctapi_common_version=7952418
rctapi_neoforge_version=7952419
rctapi_fabric_version=7952421
azurelib_version=3.1.8
wiki_exporter_fabric_version=2.2.1+1.21.1

# Compat
aether_version=1.21.1-1.5.8
