#
# Copyright (c) 2025-2026. gitoido-mc
# This Source Code Form is subject to the terms of the GNU General Public License v3.0.
# If a copy of the GNU General Public License v3.0 was not distributed with this file,
# you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
#
org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=false

# Mod Properties
group=lol.gito.radgyms

mod_id=rad_gyms
mod_name=Rad Gyms
mod_author=Gito
mod_issues=
mod_source=
license=GNU GPLv3
credits=
description=Roguelike datapackable gyms in Cobblemon!

# Mod dependencies
rctapi_min_version=0.16.0-beta
