#
# Copyright (c) 2025-2026. gitoido-mc
# This Source Code Form is subject to the terms of the GNU General Public License v3.0.
# If a copy of the GNU General Public License v3.0 was not distributed with this file,
# you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
#
org.gradle.jvmargs=-Xmx4G
org.gradle.configuration-cache=false

# Mod Properties
group=lol.gito.radgyms

mod_id=rad_gyms
mod_name=Rad Gyms
mod_author=Gito
mod_issues=https://github.com/gitoido-mc/rad-gyms/issues
mod_source=https://github.com/gitoido-mc/rad-gyms
license=GNU GPLv3
credits=Thanks to Cobblemon team for a great mod, hd42 for RCT Api, Gensir017 for original CobGyms mod!
description=Roguelike datapackable gyms in Cobblemon!

cf_id=1196570
mr_id=eF8kqlHd
