modLoader="kotlinforforge"
loaderVersion="[5.12,)"
license='''GPL-3.0-only'''


[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Rad Gyms"
credits="Big thanks to Cobblemon team, hd42 for RCT Api and Gensir for CobGyms!"
authors="Gito <corpa@gito.lol>"
description='''Roguelike gyms for Cobblemon!'''


[[mixins]]
config = "rad_gyms.mixins.json"
[[mixins]]
config = "rad_gyms.client.mixins.json"
[[mixins]]
config = "rad_gyms.neoforge.mixins.json"


[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "cobblemon"
mandatory = true
versionRange = "[${cobblemon_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="rctapi"
mandatory=true
versionRange="[${rctapi_min_version},)"
ordering="AFTER"
side="BOTH"
