modLoader="kotlinforforge"
loaderVersion="[5,)"
license='''GPL-3.0-only'''


[[mods]]
modId="rad_gyms"
version="0.4.5"
displayName="Rad Gyms"
credits="Thanks to Cobblemon team for a great mod, hd42 for RCT Api, Gensir017 for original CobGyms mod!"
authors="Gito <corpa@gito.lol>"
description='''Adds roguelike gyms in Cobblemon. RCT Api based mod.'''


[[mixins]]
config = "rad_gyms.mixins.json"
[[mixins]]
config = "rad_gyms.client.mixins.json"
[[mixins]]
config = "rad_gyms.neoforge.mixins.json"


[[dependencies.rad_gyms]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.rad_gyms]]
modId="neoforge"
type="required"
versionRange="[21.1.51,)"
ordering="NONE"
side="BOTH"

[[dependencies.rad_gyms]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.8.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.rad_gyms]]
modId="rctapi"
mandatory=true
versionRange="[0.16.0-beta,)"
ordering="AFTER"
side="BOTH"
