/*
 * Copyright (c) 2026. gitoido-mc
 * This Source Code Form is subject to the terms of the GNU General Public License v3.0.
 * If a copy of the GNU General Public License v3.0 was not distributed with this file,
 * you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
 */

package lol.gito.radgyms.fabric.datagen.provider

import com.cobblemon.mod.common.api.types.ElementalTypes
import lol.gito.radgyms.common.*
import lol.gito.radgyms.common.RadGyms.modId
import lol.gito.radgyms.common.api.serialization.RadGymsCodec
import lol.gito.radgyms.common.cache.CacheDTO
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricCodecDataProvider
import net.minecraft.core.HolderLookup
import net.minecraft.data.PackOutput
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.item.Rarity
import java.util.concurrent.CompletableFuture
import java.util.function.BiConsumer

@Suppress("LargeClass")
class CacheDataProvider(output: FabricDataOutput, lookup: CompletableFuture<HolderLookup.Provider>) :
    FabricCodecDataProvider<CacheDTO>(
        output,
        lookup,
        PackOutput.Target.DATA_PACK,
        "caches",
        RadGymsCodec.CACHE
    ) {
    override fun getName(): String = "Pokemon Caches"

    override fun configure(
        provider: BiConsumer<ResourceLocation, CacheDTO>, lookup: HolderLookup.Provider
    ) {
        val caches = mapOf(
            ElementalTypes.BUG to bugCache,
            ElementalTypes.DARK to darkCache,
            ElementalTypes.DRAGON to dragonCache,
            ElementalTypes.ELECTRIC to electricCache,
            ElementalTypes.FAIRY to fairyCache,
            ElementalTypes.FIGHTING to fightingCache,
            ElementalTypes.FIRE to fireCache,
            ElementalTypes.FLYING to flyingCache,
            ElementalTypes.GHOST to ghostCache,
            ElementalTypes.GRASS to grassCache,
            ElementalTypes.GROUND to groundCache,
            ElementalTypes.ICE to iceCache,
            ElementalTypes.NORMAL to normalCache,
            ElementalTypes.POISON to poisonCache,
            ElementalTypes.PSYCHIC to psychicCache,
            ElementalTypes.ROCK to rockCache,
            ElementalTypes.STEEL to steelCache,
            ElementalTypes.WATER to waterCache
        )

        caches.forEach {
            provider.accept(modId(it.key.showdownId), it.value)
        }
    }

    private val bugCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "caterpie" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "kakuna" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "metapod" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "paras" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "weedle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "ledyba" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "pineco" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "spinarak" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "cascoon" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "nincada" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "shedinja" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "silcoon" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "surskit" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wurmple" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "burmy" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "burmy aspect=sandy-cloak" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "burmy aspect=trash-cloak" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "combee" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "kricketot" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "venipede" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "scatterbug" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "spewpa" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wimpod" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "blipbug" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "nymble" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rellor" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tarountula" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "beedrill" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "butterfree" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "parasect" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "venonat" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "ariados" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "ledian" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "yanma" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "beautifly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dustox" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "illumise" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "volbeat" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "kricketune" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "mothim" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "wormadam" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dwebble" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "joltik" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "karrablast" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "larvesta" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sewaddle" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "shelmet" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "swadloon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "whirlipede" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "vivillon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "charjabug" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "cutiefly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "grubbin" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dottler" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "spidops" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "pinsir" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "scyther" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "venomoth" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "forretress" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "heracross" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "scizor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "shuckle" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "masquerain" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ninjask" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "vespiquen" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "yanmega" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "accelgor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "crustle" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "durant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "escavalier" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "galvantula" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "leavanny" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "scolipede" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "volcarona" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "buzzwole" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "golisopod" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "pheromosa" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ribombee" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "vikavolt" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "orbeetle" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "kleavor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lokix" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "rabsca" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=bug-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "genesect" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=bug-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "slitherwing" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val darkCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "grimer aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "meowth aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "muk aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "persian aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "raticate aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rattata aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "qwilfish aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "linoone aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "poochyena" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "zigzagoon aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "purrloin" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "samurott aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "inkay" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "impidimp" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "nickit" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "houndour" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "murkrow" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sneasel" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "mightyena" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sableye" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "deino" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "liepard" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pawniard" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "scraggy" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "vullaby" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "zorua" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "zweilous" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "morgrem" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "maschiff" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "houndoom" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "umbreon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "absol" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "honchkrow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "weavile" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bisharp" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mandibuzz" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "scrafty" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "zoroark" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "greninja aspect=bond" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "malamar" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "guzzlord" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "grimmsnarl" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "obstagoon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "thievul" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "overqwil" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "kingambit" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mabosstiff" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "moltres aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=dark-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "darkrai" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "hydreigon" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "greninja aspect=ash" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "hoopa aspect=unbound" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "yveltal" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=dark-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zarude" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "chienpao" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "chiyu" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironjugulis" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "tinglu" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "wochien" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val dragonCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "exeggutor aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "goomy aspect=region-bias-hisui" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "dreepy" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "dragonair" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dratini" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "bagon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "shelgon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gible" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "axew" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "fraxure" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "goomy" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "hakamoo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "jangmoo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "drakloak" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "arctibax" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "frigibax" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "gabite" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "altaria" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "druddigon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "haxorus" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sliggoo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cyclizar" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dragonite" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "baxcalibur" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "goodra" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "garchomp" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
            ),
            Rarity.EPIC to mapOf(
                "tatsugiri" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "latias" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "latios" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "rayquaza" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "salamence" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=dragon-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "dialga aspect=origin-forme" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "giratina aspect=origin-forme" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "palkia aspect=origin-forme" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "kyurem" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "reshiram" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zekrom" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zygarde" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "kommoo" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "necrozma aspect=ultra-fusion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=dragon-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "dragapult" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "eternatus aspect=eternamax" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "regidrago" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "roaringmoon" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val electricCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "geodude aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "golem aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "graveler aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "pikachu aspect=region-bias-alola" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "elekid" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "mareep" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "pichu" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "pichu aspect=region-bias-alola" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "electrike" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "shinx" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "blitzle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tynamo" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "helioptile" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "toxel" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "yamper" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "pawmi" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tadbulb" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wattrel" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "magnemite" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pikachu" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pikachu aspect=partner-cap" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "voltorb" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "flaaffy" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "minun" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "plusle" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "luxio" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pachirisu" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "rotom" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "eelektrik" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "emolga" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dedenne" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "togedemaru" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "morpeko" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pincurchin" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pawmo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "electabuzz" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "electrode" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "jolteon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "magneton" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "raichu" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ampharos" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "manectric" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "electivire" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "luxray" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "magnezone" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "eelektross" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "zebstrika" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "heliolisk" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "oricorio aspect=pom_pom-style" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "xurkitree" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "arctozolt" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "boltund" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dracozolt" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "toxtricity" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bellibolt" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "kilowattrel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "pawmot" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "zapdos" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "raikou" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=electric-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "thundurus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=electric-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "tapukoko" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zeraora" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "regieleki" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "miraidon" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ragingbolt" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "sandyshocks" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )

    private val fairyCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "weezing aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "cleffa" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "togepi" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "mimejr aspect=region-bias-galar" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "milcery" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tinkatink" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "clefairy" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "snubbull" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "togetic" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "flabebe" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "flabebe aspect=flower-yellow" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "flabebe aspect=flower-orange" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "flabebe aspect=flower-blue" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "flabebe aspect=flower-white" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "floette" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "spritzee" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "swirlix" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "fidough" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "tinkatuff" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "clefable" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "granbull" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "togekiss" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "aromatisse" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "florges" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "florges aspect=flower-yellow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "florges aspect=flower-orange" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "florges aspect=flower-blue" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "florges aspect=flower-white" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "slurpuff" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sylveon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "comfey" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mimikyu aspect=busted-form" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie aspect=cream-ruby" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie aspect=cream-matcha" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie aspect=cream-mint" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie aspect=cream-lemon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie aspect=cream-salted" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie aspect=cream-ruby_swirl" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie aspect=cream-caramel_swirl" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alcremie aspect=cream-rainbow_swirl" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dachsbun" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tinkaton" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=fairy-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "floette aspect=flower-eternal" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "xerneas" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "xerneas aspect=active-mode" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "magearna aspect=original-color" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=fairy-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zacian" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "enamorus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironvaliant" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "screamtail" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )

    private val fightingCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "farfetchd aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tauros aspect=paldean" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tauros aspect=blaze-breed aspect=paldean" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tauros aspect=paldean aspect=aqua-breed" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "sneasel aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tyrogue" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "makuhita" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "meditite" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "riolu" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "lilligant aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "decidueye aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "machoke" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "machop" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "mankey" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "medicham" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gurdurr" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "mienfoo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "timburr" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pancham" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "crabrawler" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "clobbopus" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "hitmonchan" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "hitmonlee" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "machamp" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "primeape" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "hitmontop" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "hariyama" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lucario" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "conkeldurr" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mienshao" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sawk" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "throh" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "hawlucha" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "pangoro" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "crabominable" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "passimian" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "falinks" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "grapploct" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sirfetchd" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sneasler" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "annihilape" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "zapdos aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=fighting-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "keldeo aspect=resolute-form" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "meloetta aspect=pirouette-forme" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "marshadow" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=fighting-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "kubfu" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "urshifu" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zamazenta" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironhands" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "koraidon" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )

    private val fireCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "marowak aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "vulpix" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "magby" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "slugma" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "charcadet" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "growlithe" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "ponyta" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "magcargo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "castform aspect=sunny-form" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "numel" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "darumaka" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pansear" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "fletchinder" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "litleo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sizzlipede" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "charmander" to CACHE_STARTER_ENTRY_WEIGHT,
                "cyndaquil aspect=region-bias-hisui" to CACHE_STARTER_ENTRY_WEIGHT,
                "cyndaquil" to CACHE_STARTER_ENTRY_WEIGHT,
                "torchic" to CACHE_STARTER_ENTRY_WEIGHT,
                "chimchar" to CACHE_STARTER_ENTRY_WEIGHT,
                "tepig" to CACHE_STARTER_ENTRY_WEIGHT,
                "fennekin" to CACHE_STARTER_ENTRY_WEIGHT,
                "litten" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "scorbunny" to CACHE_STARTER_ENTRY_WEIGHT,
                "fuecoco" to CACHE_STARTER_ENTRY_WEIGHT,
                "arcanine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "flareon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "magmar" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ninetales" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "rapidash" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "camerupt" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "torkoal" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "magmortar" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "rotom aspect=heat-appliance" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "darmanitan" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "heatmor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "simisear" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "pyroar" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "talonflame" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "blacephalon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "oricorio" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "turtonator" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "centiskorch" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "armarouge" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ceruledge" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "moltres" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "entei" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "hooh" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "groudon aspect=primal" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=fire-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "heatran" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "volcanion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=fire-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "gougingfire" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironmoth" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ogerpon aspect=hearthflame-mask" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ogerpon aspect=embody-aspect aspect=hearthflame-mask" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )

    private val flyingCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "rufflet aspect=region-bias-hisui" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "noibat" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "dartrix aspect=region-bias-hisui" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rowlet aspect=region-bias-hisui" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rookidee" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "vivillon aspect=vivillon-wings-poke-ball" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "minior aspect=meteor-form" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "corvisquire" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "squawkabilly aspect=squawkabilly-color-blue" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "squawkabilly aspect=squawkabilly-color-yellow" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "squawkabilly aspect=squawkabilly-color-gray" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "rotom aspect=fan-appliance" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "noivern" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "corviknight" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cramorant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bombirdier" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "flamigo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "shaymin" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "landorus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "thundurus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "tornadus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "enamorus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=flying-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=flying-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val ghostCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "corsola aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "typhlosion aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "duskull" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "shuppet" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "litwick" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "greavard" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "gastly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "haunter" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "misdreavus" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "drifloon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "lampent" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "yamask" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "phantump" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pumpkaboo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sandygast" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sinistea" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sinistea aspect=antique" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gimmighoul" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gimmighoul aspect=roaming" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "poltchageist aspect=artisan" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "gengar" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "banette" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dusclops" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "drifblim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dusknoir" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mismagius" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "spiritomb" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "chandelure" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cofagrigus" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "aegislash aspect=blade-forme" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gourgeist" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "trevenant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dhelmise" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mimikyu" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "oricorio aspect=sensu-style" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "palossand" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cursola" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "polteageist" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "polteageist aspect=antique" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "basculegion aspect=female" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "houndstone" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sinistcha aspect=masterpiece" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=ghost-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "giratina" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "necrozma aspect=dawn-fusion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=ghost-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "calyrex aspect=shadow-rider" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "spectrier" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "fluttermane" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val grassCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "electrode aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "voltorb aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "hoppip" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "sunkern" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "seedot" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "shroomish" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "budew" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "cherubi" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "cottonee" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "foongus" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "petilil" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "petilil aspect=region-bias-hisui" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "bounsweet" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "fomantis" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "morelull" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "steenee" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "applin" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "gossifleur" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "bramblin" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "smoliv" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "bellsprout" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "exeggcute" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gloom" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "oddish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "tangela" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "weepinbell" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "skiploom" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sunflora" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "cacnea" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "nuzleaf" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "roselia" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "snover" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "deerling aspect=summer" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "deerling aspect=autumn" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "deerling aspect=winter" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "ferroseed" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pansage" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pumpkaboo aspect=pumpkin-size-small" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pumpkaboo aspect=pumpkin-size-large" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pumpkaboo aspect=pumpkin-size-super" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "skiddo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "shiinotic" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "capsakid" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dolliv" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "poltchageist" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "chikorita" to CACHE_STARTER_ENTRY_WEIGHT,
                "bulbasaur" to CACHE_STARTER_ENTRY_WEIGHT,
                "sprigatito" to CACHE_STARTER_ENTRY_WEIGHT,
                "treecko" to CACHE_STARTER_ENTRY_WEIGHT,
                "turtwig" to CACHE_STARTER_ENTRY_WEIGHT,
                "snivy" to CACHE_STARTER_ENTRY_WEIGHT,
                "chespin" to CACHE_STARTER_ENTRY_WEIGHT,
                "rowlet" to CACHE_STARTER_ENTRY_WEIGHT,
                "grookey" to CACHE_STARTER_ENTRY_WEIGHT,
                "exeggutor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "victreebel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "vileplume" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bellossom" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "jumpluff" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "breloom" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cacturne" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "shiftry" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tropius" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "abomasnow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "carnivine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cherrim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cherrim aspect=sunshine-form" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "leafeon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "roserade" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "rotom aspect=mow-appliance" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tangrowth" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "amoonguss" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ferrothorn" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lilligant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "maractus" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sawsbuck aspect=summer" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sawsbuck aspect=autumn" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sawsbuck aspect=winter" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "simisage" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "whimsicott" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gogoat" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gourgeist aspect=pumpkin-size-small" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gourgeist aspect=pumpkin-size-large" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gourgeist aspect=pumpkin-size-super" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "kartana" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lurantis" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tsareena" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "appletun" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "eldegoss" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "flapple" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "arboliva" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "brambleghast" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dipplin" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "hydrapple" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "scovillain" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sinistcha" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=grass-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "shaymin" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "virizion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=grass-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "tapubulu" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zarude aspect=dada-cape" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "brutebonnet" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironleaves" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ogerpon" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ogerpon aspect=embody-aspect aspect=teal-mask" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val groundCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "cubone aspect=region-bias-alola" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "diglett" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "trapinch" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "sandile" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "yamask aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "cubone" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dugtrio" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "marowak" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "rhyhorn" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sandshrew" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gligar" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "phanpy" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "baltoy" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "vibrava" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "hippopotas" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "wormadam aspect=sandy-cloak" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "drilbur" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "golett" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "krokorok" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "mudbray" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "silicobra" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "toedscool" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "rhydon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sandslash" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "donphan" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "claydol" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "flygon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gastrodon aspect=east-sea" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gliscor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "hippowdon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "rhyperior" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "excadrill" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "golurk" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "krookodile" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "stunfisk" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mudsdale" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "runerigus" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sandaconda" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ursaluna" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "toedscruel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "groudon" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=ground-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "landorus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zygarde aspect=10-percent" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zygarde aspect=power-construct aspect=10-percent" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zygarde aspect=power-construct aspect=50-percent" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zygarde aspect=complete-percent" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=ground-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "greattusk" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "irontreads" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val iceCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "mrmime aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "ninetales aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "sandshrew aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "sandslash aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "vulpix aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "smoochum" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "swinub" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "spheal" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "darmanitan aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "darmanitan aspect=galarian aspect=zen-mode" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "darumaka aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "bergmite aspect=region-bias-hisui" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "snom" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "delibird" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "castform aspect=snowy-form" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sealeo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "snorunt" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "cubchoo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "vanillish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "vanillite" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "bergmite" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "cetoddle" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "jynx" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "piloswine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "glalie" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "walrein" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "froslass" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "glaceon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mamoswine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "rotom aspect=frost-appliance" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "beartic" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cryogonal" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "vanilluxe" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "avalugg" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "eiscue" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "eiscue aspect=noice_face" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "frosmoth" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mrrime" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cetitan" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "articuno" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "regice" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=ice-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "kyurem aspect=white-fusion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "kyurem aspect=black-fusion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=ice-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "calyrex aspect=ice-rider" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "glastrier" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironbundle" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val normalCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "ditto" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "jigglypuff" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "meowth" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "pidgey" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rattata" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "spearow" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "hoothoot" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "igglybuff" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "sentret" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "smeargle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "azurill" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "skitty" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "slakoth" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "taillow" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "whismur" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "zigzagoon" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "bidoof" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "happiny" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "munchlax" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "starly" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "lillipup" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "patrat" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "pidove" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "zoroark aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "zorua aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "bunnelby" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "fletchling" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "pikipek" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "yungoos" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "skwovet" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wooloo" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "lechonk" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "doduo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "eevee" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "farfetchd" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "fearow" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "lickitung" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "persian" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pidgeotto" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "porygon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "raticate" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "wigglytuff" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "aipom" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dunsparce" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "furret" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "teddiursa" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "castform" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "delcatty" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "kecleon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "linoone" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "loudred" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "spinda" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "swablu" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "vigoroth" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "bibarel" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "buneary" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "chatot" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "glameow" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "staravia" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "audino" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "deerling" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "herdier" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "minccino" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "rufflet" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "tranquill" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "watchog" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "diggersby" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gumshoos" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "stufful" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "trumbeak" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "squawkabilly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "tandemaus" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "chansey" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dodrio" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "kangaskhan" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "pidgeot" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "snorlax" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tauros" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "blissey" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "girafarig" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "miltank" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "noctowl" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "porygon2" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "stantler" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ursaring" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "exploud" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "swellow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "zangoose" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ambipom" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lickilicky" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lopunny" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "porygonz" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "purugly" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "staraptor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bouffalant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "braviary" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cinccino" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sawsbuck" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "stoutland" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "unfezant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=heart-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=star-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=diamond-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=debutante-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=matron-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=dandy-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=la_reine-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=kabuki-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "furfrou aspect=pharaoh-trim" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bewear" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "drampa" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "komala" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "oranguru" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "toucannon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dubwool" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "greedent" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "indeedee aspect=female" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ursaluna aspect=bloodmoon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "wyrdeer" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dudunsparce" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dudunsparce aspect=three-segment-form" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "farigiraf" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "maushold" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "maushold aspect=maushold-family-four" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "oinkologne" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "oinkologne aspect=female" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "slaking" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "regigigas" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "meloetta" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "typenull" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "terapagos" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val poisonCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "ekans" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "koffing aspect=region-bias-galar" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "nidoranf" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "nidoranm" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "slowbro aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "zubat" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "slowking aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wooper aspect=paldean" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "shroodle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "arbok" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "grimer" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "koffing" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "nidorina" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "nidorino" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gulpin" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "croagunk" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "skorupi" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "stunky" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "trubbish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "skrelp" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "mareanie" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "salandit" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "clodsire" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "golbat" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "muk" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "nidoking" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "nidoqueen" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "weezing" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "crobat" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "seviper" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "swalot" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "drapion" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "skuntank" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "toxicroak" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "garbodor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dragalge" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "naganadel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "poipole" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "salazzle" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "toxapex" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "toxtricity aspect=low_key-form" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "grafaiai" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=poison-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=poison-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "eternatus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "fezandipiti" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "munkidori" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "okidogi" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "pecharunt" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val psychicCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "exeggcute aspect=region-bias-alola" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "ponyta aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "raichu aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rapidash aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "slowpoke aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "kirlia" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "ralts" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wynaut" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "chingling" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "mimejr" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "braviary aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "gothita" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "munna" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "solosis" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "hatenna" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "flittle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "abra" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "drowzee" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "kadabra" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "natu" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "unown" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "wobbuffet" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "spoink" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "duosion" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "elgyem" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "gothorita" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "swoobat" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "woobat" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "espurr" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "hattrem" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "alakazam" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "hypno" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mrmime" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "espeon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "xatu" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "chimecho" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gardevoir" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "grumpig" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gallade" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "beheeyem" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "darmanitan aspect=zen-mode" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gothitelle" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "musharna" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "reuniclus" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sigilyph" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "meowstic" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "meowstic aspect=female" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "oricorio aspect=pa'u-style" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "hatterene" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "indeedee" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "espathra" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "articuno aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "mew" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "mewtwo" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "celebi" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "lugia" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "deoxys" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "deoxys aspect=attack-forme" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "deoxys aspect=defense-forme" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "deoxys aspect=speed-forme" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=psychic-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "azelf" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "cresselia" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "mesprit" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "uxie" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "victini" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "hoopa" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "cosmoem" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "cosmog" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "lunala" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "necrozma" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=psychic-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "solgaleo" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "tapulele" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "calyrex" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val rockCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "arcanine aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "growlithe aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "bonsly" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "roggenrola" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "avalugg aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rockruff" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rockruff aspect=dusk-form" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "rolycoly" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "nacli" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "geodude" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "graveler" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "kabuto" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "omanyte" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "onix" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "larvitar" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pupitar" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "sudowoodo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "anorith" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "lileep" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "nosepass" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "cranidos" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "shieldon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "archen" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "boldore" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "amaura" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "binacle" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "tyrunt" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "carkol" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "glimmet" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "naclstack" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "aerodactyl" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "golem" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "kabutops" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "omastar" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "armaldo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cradily" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lunatone" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "solrock" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bastiodon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "probopass" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "rampardos" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "archeops" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gigalith" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "aurorus" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "barbaracle" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "carbink" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tyrantrum" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lycanroc" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lycanroc aspect=midnight-form" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lycanroc aspect=dusk-form" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "minior" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "nihilego" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "stakataka" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "coalossal" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "stonjourner" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "garganacl" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "glimmora" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "klawf" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "tyranitar" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "regirock" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=rock-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "terrakion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "diancie" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=rock-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironboulder" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironthorns" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ogerpon aspect=cornerstone-mask" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ogerpon aspect=embody-aspect aspect=cornerstone-mask" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val steelCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "diglett aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "dugtrio aspect=alolan" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "meowth aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "stunfisk aspect=galarian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "goodra aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "sliggoo aspect=hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "aron" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "beldum" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "lairon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "mawile" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "metang" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "bronzor" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "wormadam aspect=trash-cloak" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "klang" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "klink" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "doublade" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "honedge" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "cufant" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "perrserker" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "varoom" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "skarmory" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "steelix" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "aggron" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bronzong" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "klinklang" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "aegislash" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "klefki" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "celesteela" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "copperajah" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "duraludon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gholdengo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "orthworm" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "revavroom" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "jirachi" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "metagross" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "registeel" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=steel-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "dialga" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "cobalion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "genesect aspect=water-drive" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "genesect aspect=electric-drive" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "genesect aspect=fire-drive" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "genesect aspect=ice-drive" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "magearna" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "necrozma aspect=dusk-fusion" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=steel-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "melmetal" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "meltan" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zacian aspect=crowned" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "zamazenta aspect=crowned" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "archaludon" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ironcrown" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
    private val waterCache = CacheDTO(
        mapOf(
            Rarity.COMMON to mapOf(
                "horsea" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "magikarp" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "marill" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wooper" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "barboach" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "feebas" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "lotad" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wingull" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "mantyke" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "basculin aspect=whitestriped" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "tympole" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "dewpider" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wishiwashi" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "arrokuda" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "chewtle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                "wiglett" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
            ),
            Rarity.UNCOMMON to mapOf(
                "goldeen" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "krabby" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "poliwag" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "poliwhirl" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "psyduck" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "seadra" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "seel" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "shellder" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "slowpoke" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "staryu" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "tentacool" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "azumarill" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "chinchou" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "corsola" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "quagsire" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "qwilfish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "remoraid" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "carvanha" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "castform aspect=rainy-form" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "clamperl" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "corphish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "lombre" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "luvdisc" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pelipper" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "wailmer" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "buizel" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "finneon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "shellos" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "shellos aspect=east-sea" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "dewott" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "ducklett" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "frillish" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "oshawott" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "palpitoad" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "panpour" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "tirtouga" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "clauncher" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "pyukumuku" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "finizen" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "wugtrio" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
            ),
            Rarity.RARE to mapOf(
                "squirtle" to CACHE_STARTER_ENTRY_WEIGHT,
                "totodile" to CACHE_STARTER_ENTRY_WEIGHT,
                "mudkip" to CACHE_STARTER_ENTRY_WEIGHT,
                "piplup" to CACHE_STARTER_ENTRY_WEIGHT,
                "oshawott aspect=region-bias-hisui" to CACHE_STARTER_ENTRY_WEIGHT,
                "froakie" to CACHE_STARTER_ENTRY_WEIGHT,
                "popplio" to CACHE_STARTER_ENTRY_WEIGHT,
                "sobble" to CACHE_STARTER_ENTRY_WEIGHT,
                "quaxly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                "cloyster" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dewgong" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "golduck" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gyarados" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "kingler" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lapras" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "poliwrath" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "seaking" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "slowbro" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "starmie" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tentacruel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "vaporeon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "kingdra" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lanturn" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "mantine" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "octillery" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "politoed" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "slowking" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "crawdaunt" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gorebyss" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "huntail" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "ludicolo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "milotic" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "relicanth" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "sharpedo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "wailord" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "whiscash" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "floatzel" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "gastrodon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "lumineon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "rotom aspect=wash-appliance" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "alomomola" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "basculin" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "basculin aspect=bluestriped" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "carracosta" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "jellicent" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "seismitoad" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "simipour" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "swanna" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "clawitzer" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "araquanid" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "bruxish" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "arctovish" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "barraskewda" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cramorant aspect=gulping-form" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "cramorant aspect=gorging-form" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dracovish" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "drednaw" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "basculegion" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "dondozo" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "palafin" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tatsugiri aspect=tatsugiri-texture-droopy" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "tatsugiri aspect=tatsugiri-texture-stretchy" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                "veluza" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE
            ),
            Rarity.EPIC to mapOf(
                "suicune" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "kyogre" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "kyogre aspect=primal" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "arceus aspect=water-plate" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "manaphy" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "palkia" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "phione" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "keldeo" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "silvally aspect=water-memory" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "tapufini" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "wishiwashi aspect=school-form" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "urshifu aspect=rapid_strike-style" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ogerpon aspect=wellspring-mask" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "ogerpon aspect=embody-aspect aspect=wellspring-mask" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "palafin aspect=hero-form" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                "walkingwake" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
            ),
        )
    )
}
