/*
 * Copyright (c) 2026. gitoido-mc
 * This Source Code Form is subject to the terms of the GNU General Public License v3.0.
 * If a copy of the GNU General Public License v3.0 was not distributed with this file,
 * you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
 */

package lol.gito.radgyms.fabric.datagen.provider

import com.cobblemon.mod.common.api.types.ElementalTypes
import lol.gito.radgyms.common.RadGyms.modId
import lol.gito.radgyms.common.api.serialization.RadGymsCodec
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput
import net.fabricmc.fabric.api.datagen.v1.provider.FabricCodecDataProvider
import net.minecraft.core.HolderLookup
import net.minecraft.data.PackOutput
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.item.Rarity
import java.util.concurrent.CompletableFuture
import java.util.function.BiConsumer

class CacheDataProvider(output: FabricDataOutput, lookup: CompletableFuture<HolderLookup.Provider>) :
    FabricCodecDataProvider<Map<String, Map<Rarity, Map<String, Int>>>>(
        output,
        lookup,
        PackOutput.Target.DATA_PACK,
        "caches",
        RadGymsCodec.CACHE
    ) {
    override fun getName(): String = "Pokemon Caches"

    override fun configure(
        provider: BiConsumer<ResourceLocation, Map<String, Map<Rarity, Map<String, Int>>>>,
        lookup: HolderLookup.Provider
    ) {
        val caches = mapOf(
            ElementalTypes.BUG to bugCache,
            ElementalTypes.DARK to darkCache,
            ElementalTypes.DRAGON to dragonCache,
            ElementalTypes.ELECTRIC to electricCache,
            ElementalTypes.FAIRY to fairyCache,
            ElementalTypes.FIGHTING to fightingCache,
            ElementalTypes.FIRE to fireCache,
            ElementalTypes.FLYING to flyingCache,
            ElementalTypes.GHOST to ghostCache,
            ElementalTypes.GRASS to grassCache,
            ElementalTypes.GROUND to groundCache,
            ElementalTypes.ICE to iceCache,
            ElementalTypes.NORMAL to normalCache,
            ElementalTypes.POISON to poisonCache,
            ElementalTypes.PSYCHIC to psychicCache,
            ElementalTypes.ROCK to rockCache,
            ElementalTypes.STEEL to steelCache,
            ElementalTypes.WATER to waterCache
        )

        caches.forEach {
            provider.accept(modId(it.key.showdownId), it.value)
        }
    }

    private val bugCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "caterpie" to 400,
                "kakuna" to 400,
                "metapod" to 400,
                "paras" to 400,
                "weedle" to 400,
                "ledyba" to 400,
                "pineco" to 400,
                "spinarak" to 400,
                "cascoon" to 400,
                "nincada" to 400,
                "shedinja" to 400,
                "silcoon" to 400,
                "surskit" to 400,
                "wurmple" to 400,
                "burmy" to 400,
                "burmy aspect=sandy-cloak" to 400,
                "burmy aspect=trash-cloak" to 400,
                "combee" to 400,
                "kricketot" to 400,
                "venipede" to 400,
                "scatterbug" to 400,
                "spewpa" to 400,
                "wimpod" to 400,
                "blipbug" to 400,
                "nymble" to 400,
                "rellor" to 400,
                "tarountula" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "beedrill" to 300,
                "butterfree" to 300,
                "parasect" to 300,
                "venonat" to 300,
                "ariados" to 300,
                "ledian" to 300,
                "yanma" to 300,
                "beautifly" to 300,
                "dustox" to 300,
                "illumise" to 300,
                "volbeat" to 300,
                "kricketune" to 300,
                "mothim" to 300,
                "wormadam" to 300,
                "dwebble" to 300,
                "joltik" to 300,
                "karrablast" to 300,
                "larvesta" to 300,
                "sewaddle" to 300,
                "shelmet" to 300,
                "swadloon" to 300,
                "whirlipede" to 300,
                "vivillon" to 300,
                "charjabug" to 300,
                "cutiefly" to 300,
                "grubbin" to 300,
                "dottler" to 300,
                "spidops" to 300
            ),
            Rarity.RARE to mapOf(
                "pinsir" to 200,
                "scyther" to 200,
                "venomoth" to 200,
                "forretress" to 200,
                "heracross" to 200,
                "scizor" to 200,
                "shuckle" to 200,
                "masquerain" to 200,
                "ninjask" to 200,
                "vespiquen" to 200,
                "yanmega" to 200,
                "accelgor" to 200,
                "crustle" to 200,
                "durant" to 200,
                "escavalier" to 200,
                "galvantula" to 200,
                "leavanny" to 200,
                "scolipede" to 200,
                "volcarona" to 200,
                "buzzwole" to 200,
                "golisopod" to 200,
                "pheromosa" to 200,
                "ribombee" to 200,
                "vikavolt" to 200,
                "orbeetle" to 200,
                "kleavor" to 200,
                "lokix" to 200,
                "rabsca" to 200
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=bug-plate" to 100,
                "genesect" to 100,
                "silvally aspect=bug-memory" to 100,
                "slitherwing" to 100
            ),
        )
    )
    private val darkCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "grimer aspect=alolan" to 400,
                "meowth aspect=alolan" to 400,
                "muk aspect=alolan" to 400,
                "persian aspect=alolan" to 400,
                "raticate aspect=alolan" to 400,
                "rattata aspect=alolan" to 400,
                "qwilfish aspect=hisuian" to 400,
                "linoone aspect=galarian" to 400,
                "poochyena" to 400,
                "zigzagoon aspect=galarian" to 400,
                "purrloin" to 400,
                "samurott aspect=hisuian" to 400,
                "inkay" to 400,
                "impidimp" to 400,
                "nickit" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "houndour" to 300,
                "murkrow" to 300,
                "sneasel" to 300,
                "mightyena" to 300,
                "sableye" to 300,
                "deino" to 300,
                "liepard" to 300,
                "pawniard" to 300,
                "scraggy" to 300,
                "vullaby" to 300,
                "zorua" to 300,
                "zweilous" to 300,
                "morgrem" to 300,
                "maschiff" to 300
            ),
            Rarity.RARE to mapOf(
                "houndoom" to 200,
                "umbreon" to 200,
                "absol" to 200,
                "honchkrow" to 200,
                "weavile" to 200,
                "bisharp" to 200,
                "mandibuzz" to 200,
                "scrafty" to 200,
                "zoroark" to 200,
                "greninja aspect=bond" to 200,
                "malamar" to 200,
                "guzzlord" to 200,
                "grimmsnarl" to 200,
                "obstagoon" to 200,
                "thievul" to 200,
                "overqwil" to 200,
                "kingambit" to 200,
                "mabosstiff" to 200
            ),
            Rarity.EPIC to mapOf(
                "moltres aspect=galarian" to 100,
                "arceus aspect=dark-plate" to 100,
                "darkrai" to 100,
                "hydreigon" to 100,
                "greninja aspect=ash" to 100,
                "hoopa aspect=unbound" to 100,
                "yveltal" to 100,
                "silvally aspect=dark-memory" to 100,
                "zarude" to 100,
                "chienpao" to 100,
                "chiyu" to 100,
                "ironjugulis" to 100,
                "tinglu" to 100,
                "wochien" to 100
            ),
        )
    )
    private val dragonCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "exeggutor aspect=alolan" to 400,
                "goomy aspect=region-bias-hisui" to 400,
                "dreepy" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "dragonair" to 300,
                "dratini" to 300,
                "bagon" to 300,
                "shelgon" to 300,
                "gible" to 300,
                "axew" to 300,
                "fraxure" to 300,
                "goomy" to 300,
                "hakamoo" to 300,
                "jangmoo" to 300,
                "drakloak" to 300,
                "arctibax" to 300,
                "frigibax" to 300
            ),
            Rarity.RARE to mapOf(
                "gabite" to 200,
                "altaria" to 200,
                "druddigon" to 200,
                "haxorus" to 200,
                "sliggoo" to 200,
                "cyclizar" to 200,
                "dragonite" to 200,
                "baxcalibur" to 200,
                "goodra" to 200,
                "garchomp" to 200,
            ),
            Rarity.EPIC to mapOf(
                "tatsugiri" to 100,
                "latias" to 100,
                "latios" to 100,
                "rayquaza" to 100,
                "salamence" to 100,
                "arceus aspect=dragon-plate" to 100,
                "dialga aspect=origin-forme" to 100,
                "giratina aspect=origin-forme" to 100,
                "palkia aspect=origin-forme" to 100,
                "kyurem" to 100,
                "reshiram" to 100,
                "zekrom" to 100,
                "zygarde" to 100,
                "kommoo" to 100,
                "necrozma aspect=ultra-fusion" to 100,
                "silvally aspect=dragon-memory" to 100,
                "dragapult" to 100,
                "eternatus aspect=eternamax" to 100,
                "regidrago" to 100,
                "roaringmoon" to 100
            ),
        )
    )
    private val electricCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "geodude aspect=alolan" to 400,
                "golem aspect=alolan" to 400,
                "graveler aspect=alolan" to 400,
                "pikachu aspect=region-bias-alola" to 400,
                "elekid" to 400,
                "mareep" to 400,
                "pichu" to 400,
                "pichu aspect=region-bias-alola" to 400,
                "electrike" to 400,
                "shinx" to 400,
                "blitzle" to 400,
                "tynamo" to 400,
                "helioptile" to 400,
                "toxel" to 400,
                "yamper" to 400,
                "pawmi" to 400,
                "tadbulb" to 400,
                "wattrel" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "magnemite" to 300,
                "pikachu" to 300,
                "pikachu aspect=partner-cap" to 300,
                "voltorb" to 300,
                "flaaffy" to 300,
                "minun" to 300,
                "plusle" to 300,
                "luxio" to 300,
                "pachirisu" to 300,
                "rotom" to 300,
                "eelektrik" to 300,
                "emolga" to 300,
                "dedenne" to 300,
                "togedemaru" to 300,
                "morpeko" to 300,
                "pincurchin" to 300,
                "pawmo" to 300
            ),
            Rarity.RARE to mapOf(
                "electabuzz" to 200,
                "electrode" to 200,
                "jolteon" to 200,
                "magneton" to 200,
                "raichu" to 200,
                "ampharos" to 200,
                "manectric" to 200,
                "electivire" to 200,
                "luxray" to 200,
                "magnezone" to 200,
                "eelektross" to 200,
                "zebstrika" to 200,
                "heliolisk" to 200,
                "oricorio aspect=pom_pom-style" to 200,
                "xurkitree" to 200,
                "arctozolt" to 200,
                "boltund" to 200,
                "dracozolt" to 200,
                "toxtricity" to 200,
                "bellibolt" to 200,
                "kilowattrel" to 200,
                "pawmot" to 200
            ),
            Rarity.EPIC to mapOf(
                "zapdos" to 100,
                "raikou" to 100,
                "arceus aspect=electric-plate" to 100,
                "thundurus" to 100,
                "silvally aspect=electric-memory" to 100,
                "tapukoko" to 100,
                "zeraora" to 100,
                "regieleki" to 100,
                "miraidon" to 100,
                "ragingbolt" to 100,
                "sandyshocks" to 100
            ),
        )
    )

    private val fairyCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "weezing aspect=galarian" to 400,
                "cleffa" to 400,
                "togepi" to 400,
                "mimejr aspect=region-bias-galar" to 400,
                "milcery" to 400,
                "tinkatink" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "clefairy" to 300,
                "snubbull" to 300,
                "togetic" to 300,
                "flabebe" to 300,
                "flabebe aspect=flower-yellow" to 300,
                "flabebe aspect=flower-orange" to 300,
                "flabebe aspect=flower-blue" to 300,
                "flabebe aspect=flower-white" to 300,
                "floette" to 300,
                "spritzee" to 300,
                "swirlix" to 300,
                "fidough" to 300,
                "tinkatuff" to 300
            ),
            Rarity.RARE to mapOf(
                "clefable" to 200,
                "granbull" to 200,
                "togekiss" to 200,
                "aromatisse" to 200,
                "florges" to 200,
                "florges aspect=flower-yellow" to 200,
                "florges aspect=flower-orange" to 200,
                "florges aspect=flower-blue" to 200,
                "florges aspect=flower-white" to 200,
                "slurpuff" to 200,
                "sylveon" to 200,
                "comfey" to 200,
                "mimikyu aspect=busted-form" to 200,
                "alcremie" to 200,
                "alcremie aspect=cream-ruby" to 200,
                "alcremie aspect=cream-matcha" to 200,
                "alcremie aspect=cream-mint" to 200,
                "alcremie aspect=cream-lemon" to 200,
                "alcremie aspect=cream-salted" to 200,
                "alcremie aspect=cream-ruby_swirl" to 200,
                "alcremie aspect=cream-caramel_swirl" to 200,
                "alcremie aspect=cream-rainbow_swirl" to 200,
                "dachsbun" to 200,
                "tinkaton" to 200
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=fairy-plate" to 100,
                "floette aspect=flower-eternal" to 100,
                "xerneas" to 100,
                "xerneas aspect=active-mode" to 100,
                "magearna aspect=original-color" to 100,
                "silvally aspect=fairy-memory" to 100,
                "zacian" to 100,
                "enamorus" to 100,
                "ironvaliant" to 100,
                "screamtail" to 100
            ),
        )
    )

    private val fightingCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "farfetchd aspect=galarian" to 400,
                "tauros aspect=paldean" to 400,
                "tauros aspect=blaze-breed aspect=paldean" to 400,
                "tauros aspect=paldean aspect=aqua-breed" to 400,
                "sneasel aspect=hisuian" to 400,
                "tyrogue" to 400,
                "makuhita" to 400,
                "meditite" to 400,
                "riolu" to 400,
                "lilligant aspect=hisuian" to 400,
                "decidueye aspect=hisuian" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "machoke" to 300,
                "machop" to 300,
                "mankey" to 300,
                "medicham" to 300,
                "gurdurr" to 300,
                "mienfoo" to 300,
                "timburr" to 300,
                "pancham" to 300,
                "crabrawler" to 300,
                "clobbopus" to 300
            ),
            Rarity.RARE to mapOf(
                "hitmonchan" to 200,
                "hitmonlee" to 200,
                "machamp" to 200,
                "primeape" to 200,
                "hitmontop" to 200,
                "hariyama" to 200,
                "lucario" to 200,
                "conkeldurr" to 200,
                "mienshao" to 200,
                "sawk" to 200,
                "throh" to 200,
                "hawlucha" to 200,
                "pangoro" to 200,
                "crabominable" to 200,
                "passimian" to 200,
                "falinks" to 200,
                "grapploct" to 200,
                "sirfetchd" to 200,
                "sneasler" to 200,
                "annihilape" to 200
            ),
            Rarity.EPIC to mapOf(
                "zapdos aspect=galarian" to 100,
                "arceus aspect=fighting-plate" to 100,
                "keldeo aspect=resolute-form" to 100,
                "meloetta aspect=pirouette-forme" to 100,
                "marshadow" to 100,
                "silvally aspect=fighting-memory" to 100,
                "kubfu" to 100,
                "urshifu" to 100,
                "zamazenta" to 100,
                "ironhands" to 100,
                "koraidon" to 100
            ),
        )
    )

    private val fireCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "marowak aspect=alolan" to 400,
                "vulpix" to 400,
                "magby" to 400,
                "slugma" to 400,
                "charcadet" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "growlithe" to 300,
                "ponyta" to 300,
                "magcargo" to 300,
                "castform aspect=sunny-form" to 300,
                "numel" to 300,
                "darumaka" to 300,
                "pansear" to 300,
                "fletchinder" to 300,
                "litleo" to 300,
                "sizzlipede" to 300
            ),
            Rarity.RARE to mapOf(
                "charmander" to 150,
                "cyndaquil aspect=region-bias-hisui" to 150,
                "cyndaquil" to 150,
                "torchic" to 150,
                "chimchar" to 150,
                "tepig" to 150,
                "fennekin" to 150,
                "litten" to 300,
                "scorbunny" to 150,
                "fuecoco" to 150,
                "arcanine" to 200,
                "flareon" to 200,
                "magmar" to 200,
                "ninetales" to 200,
                "rapidash" to 200,
                "camerupt" to 200,
                "torkoal" to 200,
                "magmortar" to 200,
                "rotom aspect=heat-appliance" to 200,
                "darmanitan" to 200,
                "heatmor" to 200,
                "simisear" to 200,
                "pyroar" to 200,
                "talonflame" to 200,
                "blacephalon" to 200,
                "oricorio" to 200,
                "turtonator" to 200,
                "centiskorch" to 200,
                "armarouge" to 200,
                "ceruledge" to 200
            ),
            Rarity.EPIC to mapOf(
                "moltres" to 100,
                "entei" to 100,
                "hooh" to 100,
                "groudon aspect=primal" to 100,
                "arceus aspect=fire-plate" to 100,
                "heatran" to 100,
                "volcanion" to 100,
                "silvally aspect=fire-memory" to 100,
                "gougingfire" to 100,
                "ironmoth" to 100,
                "ogerpon aspect=hearthflame-mask" to 100,
                "ogerpon aspect=embody-aspect aspect=hearthflame-mask" to 100
            ),
        )
    )

    private val flyingCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "rufflet aspect=region-bias-hisui" to 400,
                "noibat" to 400,
                "dartrix aspect=region-bias-hisui" to 400,
                "rowlet aspect=region-bias-hisui" to 400,
                "rookidee" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "vivillon aspect=vivillon-wings-poke-ball" to 300,
                "minior aspect=meteor-form" to 300,
                "corvisquire" to 300,
                "squawkabilly aspect=squawkabilly-color-blue" to 300,
                "squawkabilly aspect=squawkabilly-color-yellow" to 300,
                "squawkabilly aspect=squawkabilly-color-gray" to 300
            ),
            Rarity.RARE to mapOf(
                "rotom aspect=fan-appliance" to 200,
                "noivern" to 200,
                "corviknight" to 200,
                "cramorant" to 200,
                "bombirdier" to 200,
                "flamigo" to 200
            ),
            Rarity.EPIC to mapOf(
                "shaymin" to 100,
                "landorus" to 100,
                "thundurus" to 100,
                "tornadus" to 100,
                "enamorus" to 100,
                "arceus aspect=flying-plate" to 100,
                "silvally aspect=flying-memory" to 100
            ),
        )
    )
    private val ghostCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "corsola aspect=galarian" to 400,
                "typhlosion aspect=hisuian" to 400,
                "duskull" to 400,
                "shuppet" to 400,
                "litwick" to 400,
                "greavard" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "gastly" to 300,
                "haunter" to 300,
                "misdreavus" to 300,
                "drifloon" to 300,
                "lampent" to 300,
                "yamask" to 300,
                "phantump" to 300,
                "pumpkaboo" to 300,
                "sandygast" to 300,
                "sinistea" to 300,
                "sinistea aspect=antique" to 300,
                "gimmighoul" to 300,
                "gimmighoul aspect=roaming" to 300,
                "poltchageist aspect=artisan" to 300
            ),
            Rarity.RARE to mapOf(
                "gengar" to 200,
                "banette" to 200,
                "dusclops" to 200,
                "drifblim" to 200,
                "dusknoir" to 200,
                "mismagius" to 200,
                "spiritomb" to 200,
                "chandelure" to 200,
                "cofagrigus" to 200,
                "aegislash aspect=blade-forme" to 200,
                "gourgeist" to 200,
                "trevenant" to 200,
                "dhelmise" to 200,
                "mimikyu" to 200,
                "oricorio aspect=sensu-style" to 200,
                "palossand" to 200,
                "cursola" to 200,
                "polteageist" to 200,
                "polteageist aspect=antique" to 200,
                "basculegion aspect=female" to 200,
                "houndstone" to 200,
                "sinistcha aspect=masterpiece" to 200
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=ghost-plate" to 100,
                "giratina" to 100,
                "necrozma aspect=dawn-fusion" to 100,
                "silvally aspect=ghost-memory" to 100,
                "calyrex aspect=shadow-rider" to 100,
                "spectrier" to 100,
                "fluttermane" to 100
            ),
        )
    )
    private val grassCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "electrode aspect=hisuian" to 400,
                "voltorb aspect=hisuian" to 400,
                "hoppip" to 400,
                "sunkern" to 400,
                "seedot" to 400,
                "shroomish" to 400,
                "budew" to 400,
                "cherubi" to 400,
                "cottonee" to 400,
                "foongus" to 400,
                "petilil" to 400,
                "petilil aspect=region-bias-hisui" to 400,
                "bounsweet" to 400,
                "fomantis" to 400,
                "morelull" to 400,
                "steenee" to 400,
                "applin" to 400,
                "gossifleur" to 400,
                "bramblin" to 400,
                "smoliv" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "bellsprout" to 300,
                "exeggcute" to 300,
                "gloom" to 300,
                "oddish" to 300,
                "tangela" to 300,
                "weepinbell" to 300,
                "skiploom" to 300,
                "sunflora" to 300,
                "cacnea" to 300,
                "nuzleaf" to 300,
                "roselia" to 300,
                "snover" to 300,
                "deerling aspect=summer" to 300,
                "deerling aspect=autumn" to 300,
                "deerling aspect=winter" to 300,
                "ferroseed" to 300,
                "pansage" to 300,
                "pumpkaboo aspect=pumpkin-size-small" to 300,
                "pumpkaboo aspect=pumpkin-size-large" to 300,
                "pumpkaboo aspect=pumpkin-size-super" to 300,
                "skiddo" to 300,
                "shiinotic" to 300,
                "capsakid" to 300,
                "dolliv" to 300,
                "poltchageist" to 300
            ),
            Rarity.RARE to mapOf(
                "chikorita" to 150,
                "bulbasaur" to 150,
                "sprigatito" to 150,
                "treecko" to 150,
                "turtwig" to 150,
                "snivy" to 150,
                "chespin" to 150,
                "rowlet" to 150,
                "grookey" to 150,
                "exeggutor" to 200,
                "victreebel" to 200,
                "vileplume" to 200,
                "bellossom" to 200,
                "jumpluff" to 200,
                "breloom" to 200,
                "cacturne" to 200,
                "shiftry" to 200,
                "tropius" to 200,
                "abomasnow" to 200,
                "carnivine" to 200,
                "cherrim" to 200,
                "cherrim aspect=sunshine-form" to 200,
                "leafeon" to 200,
                "roserade" to 200,
                "rotom aspect=mow-appliance" to 200,
                "tangrowth" to 200,
                "amoonguss" to 200,
                "ferrothorn" to 200,
                "lilligant" to 200,
                "maractus" to 200,
                "sawsbuck aspect=summer" to 200,
                "sawsbuck aspect=autumn" to 200,
                "sawsbuck aspect=winter" to 200,
                "simisage" to 200,
                "whimsicott" to 200,
                "gogoat" to 200,
                "gourgeist aspect=pumpkin-size-small" to 200,
                "gourgeist aspect=pumpkin-size-large" to 200,
                "gourgeist aspect=pumpkin-size-super" to 200,
                "kartana" to 200,
                "lurantis" to 200,
                "tsareena" to 200,
                "appletun" to 200,
                "eldegoss" to 200,
                "flapple" to 200,
                "arboliva" to 200,
                "brambleghast" to 200,
                "dipplin" to 200,
                "hydrapple" to 200,
                "scovillain" to 200,
                "sinistcha" to 200
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=grass-plate" to 100,
                "shaymin" to 100,
                "virizion" to 100,
                "silvally aspect=grass-memory" to 100,
                "tapubulu" to 100,
                "zarude aspect=dada-cape" to 100,
                "brutebonnet" to 100,
                "ironleaves" to 100,
                "ogerpon" to 100,
                "ogerpon aspect=embody-aspect aspect=teal-mask" to 100
            ),
        )
    )
    private val groundCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "cubone aspect=region-bias-alola" to 400,
                "diglett" to 400,
                "trapinch" to 400,
                "sandile" to 400,
                "yamask aspect=galarian" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "cubone" to 300,
                "dugtrio" to 300,
                "marowak" to 300,
                "rhyhorn" to 300,
                "sandshrew" to 300,
                "gligar" to 300,
                "phanpy" to 300,
                "baltoy" to 300,
                "vibrava" to 300,
                "hippopotas" to 300,
                "wormadam aspect=sandy-cloak" to 300,
                "drilbur" to 300,
                "golett" to 300,
                "krokorok" to 300,
                "mudbray" to 300,
                "silicobra" to 300,
                "toedscool" to 300
            ),
            Rarity.RARE to mapOf(
                "rhydon" to 200,
                "sandslash" to 200,
                "donphan" to 200,
                "claydol" to 200,
                "flygon" to 200,
                "gastrodon aspect=east-sea" to 200,
                "gliscor" to 200,
                "hippowdon" to 200,
                "rhyperior" to 200,
                "excadrill" to 200,
                "golurk" to 200,
                "krookodile" to 200,
                "stunfisk" to 200,
                "mudsdale" to 200,
                "runerigus" to 200,
                "sandaconda" to 200,
                "ursaluna" to 200,
                "toedscruel" to 200
            ),
            Rarity.EPIC to mapOf(
                "groudon" to 100,
                "arceus aspect=ground-plate" to 100,
                "landorus" to 100,
                "zygarde aspect=10-percent" to 100,
                "zygarde aspect=power-construct aspect=10-percent" to 100,
                "zygarde aspect=power-construct aspect=50-percent" to 100,
                "zygarde aspect=complete-percent" to 100,
                "silvally aspect=ground-memory" to 100,
                "greattusk" to 100,
                "irontreads" to 100
            ),
        )
    )
    private val iceCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "mrmime aspect=galarian" to 400,
                "ninetales aspect=alolan" to 400,
                "sandshrew aspect=alolan" to 400,
                "sandslash aspect=alolan" to 400,
                "vulpix aspect=alolan" to 400,
                "smoochum" to 400,
                "swinub" to 400,
                "spheal" to 400,
                "darmanitan aspect=galarian" to 400,
                "darmanitan aspect=galarian aspect=zen-mode" to 400,
                "darumaka aspect=galarian" to 400,
                "bergmite aspect=region-bias-hisui" to 400,
                "snom" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "delibird" to 300,
                "castform aspect=snowy-form" to 300,
                "sealeo" to 300,
                "snorunt" to 300,
                "cubchoo" to 300,
                "vanillish" to 300,
                "vanillite" to 300,
                "bergmite" to 300,
                "cetoddle" to 300
            ),
            Rarity.RARE to mapOf(
                "jynx" to 200,
                "piloswine" to 200,
                "glalie" to 200,
                "walrein" to 200,
                "froslass" to 200,
                "glaceon" to 200,
                "mamoswine" to 200,
                "rotom aspect=frost-appliance" to 200,
                "beartic" to 200,
                "cryogonal" to 200,
                "vanilluxe" to 200,
                "avalugg" to 200,
                "eiscue" to 200,
                "eiscue aspect=noice_face" to 200,
                "frosmoth" to 200,
                "mrrime" to 200,
                "cetitan" to 200
            ),
            Rarity.EPIC to mapOf(
                "articuno" to 100,
                "regice" to 100,
                "arceus aspect=ice-plate" to 100,
                "kyurem aspect=white-fusion" to 100,
                "kyurem aspect=black-fusion" to 100,
                "silvally aspect=ice-memory" to 100,
                "calyrex aspect=ice-rider" to 100,
                "glastrier" to 100,
                "ironbundle" to 100
            ),
        )
    )
    private val normalCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "ditto" to 400,
                "jigglypuff" to 400,
                "meowth" to 400,
                "pidgey" to 400,
                "rattata" to 400,
                "spearow" to 400,
                "hoothoot" to 400,
                "igglybuff" to 400,
                "sentret" to 400,
                "smeargle" to 400,
                "azurill" to 400,
                "skitty" to 400,
                "slakoth" to 400,
                "taillow" to 400,
                "whismur" to 400,
                "zigzagoon" to 400,
                "bidoof" to 400,
                "happiny" to 400,
                "munchlax" to 400,
                "starly" to 400,
                "lillipup" to 400,
                "patrat" to 400,
                "pidove" to 400,
                "zoroark aspect=hisuian" to 400,
                "zorua aspect=hisuian" to 400,
                "bunnelby" to 400,
                "fletchling" to 400,
                "pikipek" to 400,
                "yungoos" to 400,
                "skwovet" to 400,
                "wooloo" to 400,
                "lechonk" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "doduo" to 300,
                "eevee" to 300,
                "farfetchd" to 300,
                "fearow" to 300,
                "lickitung" to 300,
                "persian" to 300,
                "pidgeotto" to 300,
                "porygon" to 300,
                "raticate" to 300,
                "wigglytuff" to 300,
                "aipom" to 300,
                "dunsparce" to 300,
                "furret" to 300,
                "teddiursa" to 300,
                "castform" to 300,
                "delcatty" to 300,
                "kecleon" to 300,
                "linoone" to 300,
                "loudred" to 300,
                "spinda" to 300,
                "swablu" to 300,
                "vigoroth" to 300,
                "bibarel" to 300,
                "buneary" to 300,
                "chatot" to 300,
                "glameow" to 300,
                "staravia" to 300,
                "audino" to 300,
                "deerling" to 300,
                "herdier" to 300,
                "minccino" to 300,
                "rufflet" to 300,
                "tranquill" to 300,
                "watchog" to 300,
                "diggersby" to 300,
                "gumshoos" to 300,
                "stufful" to 300,
                "trumbeak" to 300,
                "squawkabilly" to 300,
                "tandemaus" to 300
            ),
            Rarity.RARE to mapOf(
                "chansey" to 200,
                "dodrio" to 200,
                "kangaskhan" to 200,
                "pidgeot" to 200,
                "snorlax" to 200,
                "tauros" to 200,
                "blissey" to 200,
                "girafarig" to 200,
                "miltank" to 200,
                "noctowl" to 200,
                "porygon2" to 200,
                "stantler" to 200,
                "ursaring" to 200,
                "exploud" to 200,
                "swellow" to 200,
                "zangoose" to 200,
                "ambipom" to 200,
                "lickilicky" to 200,
                "lopunny" to 200,
                "porygonz" to 200,
                "purugly" to 200,
                "staraptor" to 200,
                "bouffalant" to 200,
                "braviary" to 200,
                "cinccino" to 200,
                "sawsbuck" to 200,
                "stoutland" to 200,
                "unfezant" to 200,
                "furfrou" to 200,
                "furfrou aspect=heart-trim" to 200,
                "furfrou aspect=star-trim" to 200,
                "furfrou aspect=diamond-trim" to 200,
                "furfrou aspect=debutante-trim" to 200,
                "furfrou aspect=matron-trim" to 200,
                "furfrou aspect=dandy-trim" to 200,
                "furfrou aspect=la_reine-trim" to 200,
                "furfrou aspect=kabuki-trim" to 200,
                "furfrou aspect=pharaoh-trim" to 200,
                "bewear" to 200,
                "drampa" to 200,
                "komala" to 200,
                "oranguru" to 200,
                "toucannon" to 200,
                "dubwool" to 200,
                "greedent" to 200,
                "indeedee aspect=female" to 200,
                "ursaluna aspect=bloodmoon" to 200,
                "wyrdeer" to 200,
                "dudunsparce" to 200,
                "dudunsparce aspect=three-segment-form" to 200,
                "farigiraf" to 200,
                "maushold" to 200,
                "maushold aspect=maushold-family-four" to 200,
                "oinkologne" to 200,
                "oinkologne aspect=female" to 200
            ),
            Rarity.EPIC to mapOf(
                "slaking" to 100,
                "arceus" to 100,
                "regigigas" to 100,
                "meloetta" to 100,
                "silvally" to 100,
                "typenull" to 100,
                "terapagos" to 100
            ),
        )
    )
    private val poisonCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "ekans" to 400,
                "koffing aspect=region-bias-galar" to 400,
                "nidoranf" to 400,
                "nidoranm" to 400,
                "slowbro aspect=galarian" to 400,
                "zubat" to 400,
                "slowking aspect=galarian" to 400,
                "wooper aspect=paldean" to 400,
                "shroodle" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "arbok" to 300,
                "grimer" to 300,
                "koffing" to 300,
                "nidorina" to 300,
                "nidorino" to 300,
                "gulpin" to 300,
                "croagunk" to 300,
                "skorupi" to 300,
                "stunky" to 300,
                "trubbish" to 300,
                "skrelp" to 300,
                "mareanie" to 300,
                "salandit" to 300,
                "clodsire" to 300
            ),
            Rarity.RARE to mapOf(
                "golbat" to 200,
                "muk" to 200,
                "nidoking" to 200,
                "nidoqueen" to 200,
                "weezing" to 200,
                "crobat" to 200,
                "seviper" to 200,
                "swalot" to 200,
                "drapion" to 200,
                "skuntank" to 200,
                "toxicroak" to 200,
                "garbodor" to 200,
                "dragalge" to 200,
                "naganadel" to 200,
                "poipole" to 200,
                "salazzle" to 200,
                "toxapex" to 200,
                "toxtricity aspect=low_key-form" to 200,
                "grafaiai" to 200
            ),
            Rarity.EPIC to mapOf(
                "arceus aspect=poison-plate" to 100,
                "silvally aspect=poison-memory" to 100,
                "eternatus" to 100,
                "fezandipiti" to 100,
                "munkidori" to 100,
                "okidogi" to 100,
                "pecharunt" to 100
            ),
        )
    )
    private val psychicCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "exeggcute aspect=region-bias-alola" to 400,
                "ponyta aspect=galarian" to 400,
                "raichu aspect=alolan" to 400,
                "rapidash aspect=galarian" to 400,
                "slowpoke aspect=galarian" to 400,
                "kirlia" to 400,
                "ralts" to 400,
                "wynaut" to 400,
                "chingling" to 400,
                "mimejr" to 400,
                "braviary aspect=hisuian" to 400,
                "gothita" to 400,
                "munna" to 400,
                "solosis" to 400,
                "hatenna" to 400,
                "flittle" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "abra" to 300,
                "drowzee" to 300,
                "kadabra" to 300,
                "natu" to 300,
                "unown" to 300,
                "wobbuffet" to 300,
                "spoink" to 300,
                "duosion" to 300,
                "elgyem" to 300,
                "gothorita" to 300,
                "swoobat" to 300,
                "woobat" to 300,
                "espurr" to 300,
                "hattrem" to 300
            ),
            Rarity.RARE to mapOf(
                "alakazam" to 200,
                "hypno" to 200,
                "mrmime" to 200,
                "espeon" to 200,
                "xatu" to 200,
                "chimecho" to 200,
                "gardevoir" to 200,
                "grumpig" to 200,
                "gallade" to 200,
                "beheeyem" to 200,
                "darmanitan aspect=zen-mode" to 200,
                "gothitelle" to 200,
                "musharna" to 200,
                "reuniclus" to 200,
                "sigilyph" to 200,
                "meowstic" to 200,
                "meowstic aspect=female" to 200,
                "oricorio aspect=pa'u-style" to 200,
                "hatterene" to 200,
                "indeedee" to 200,
                "espathra" to 200
            ),
            Rarity.EPIC to mapOf(
                "articuno aspect=galarian" to 100,
                "mew" to 100,
                "mewtwo" to 100,
                "celebi" to 100,
                "lugia" to 100,
                "deoxys" to 100,
                "deoxys aspect=attack-forme" to 100,
                "deoxys aspect=defense-forme" to 100,
                "deoxys aspect=speed-forme" to 100,
                "arceus aspect=psychic-plate" to 100,
                "azelf" to 100,
                "cresselia" to 100,
                "mesprit" to 100,
                "uxie" to 100,
                "victini" to 100,
                "hoopa" to 100,
                "cosmoem" to 100,
                "cosmog" to 100,
                "lunala" to 100,
                "necrozma" to 100,
                "silvally aspect=psychic-memory" to 100,
                "solgaleo" to 100,
                "tapulele" to 100,
                "calyrex" to 100
            ),
        )
    )
    private val rockCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "arcanine aspect=hisuian" to 400,
                "growlithe aspect=hisuian" to 400,
                "bonsly" to 400,
                "roggenrola" to 400,
                "avalugg aspect=hisuian" to 400,
                "rockruff" to 400,
                "rockruff aspect=dusk-form" to 400,
                "rolycoly" to 400,
                "nacli" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "geodude" to 300,
                "graveler" to 300,
                "kabuto" to 300,
                "omanyte" to 300,
                "onix" to 300,
                "larvitar" to 300,
                "pupitar" to 300,
                "sudowoodo" to 300,
                "anorith" to 300,
                "lileep" to 300,
                "nosepass" to 300,
                "cranidos" to 300,
                "shieldon" to 300,
                "archen" to 300,
                "boldore" to 300,
                "amaura" to 300,
                "binacle" to 300,
                "tyrunt" to 300,
                "carkol" to 300,
                "glimmet" to 300,
                "naclstack" to 300
            ),
            Rarity.RARE to mapOf(
                "aerodactyl" to 200,
                "golem" to 200,
                "kabutops" to 200,
                "omastar" to 200,
                "armaldo" to 200,
                "cradily" to 200,
                "lunatone" to 200,
                "solrock" to 200,
                "bastiodon" to 200,
                "probopass" to 200,
                "rampardos" to 200,
                "archeops" to 200,
                "gigalith" to 200,
                "aurorus" to 200,
                "barbaracle" to 200,
                "carbink" to 200,
                "tyrantrum" to 200,
                "lycanroc" to 200,
                "lycanroc aspect=midnight-form" to 200,
                "lycanroc aspect=dusk-form" to 200,
                "minior" to 200,
                "nihilego" to 200,
                "stakataka" to 200,
                "coalossal" to 200,
                "stonjourner" to 200,
                "garganacl" to 200,
                "glimmora" to 200,
                "klawf" to 200
            ),
            Rarity.EPIC to mapOf(
                "tyranitar" to 100,
                "regirock" to 100,
                "arceus aspect=rock-plate" to 100,
                "terrakion" to 100,
                "diancie" to 100,
                "silvally aspect=rock-memory" to 100,
                "ironboulder" to 100,
                "ironthorns" to 100,
                "ogerpon aspect=cornerstone-mask" to 100,
                "ogerpon aspect=embody-aspect aspect=cornerstone-mask" to 100
            ),
        )
    )
    private val steelCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "diglett aspect=alolan" to 400,
                "dugtrio aspect=alolan" to 400,
                "meowth aspect=galarian" to 400,
                "stunfisk aspect=galarian" to 400,
                "goodra aspect=hisuian" to 400,
                "sliggoo aspect=hisuian" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "aron" to 300,
                "beldum" to 300,
                "lairon" to 300,
                "mawile" to 300,
                "metang" to 300,
                "bronzor" to 300,
                "wormadam aspect=trash-cloak" to 300,
                "klang" to 300,
                "klink" to 300,
                "doublade" to 300,
                "honedge" to 300,
                "cufant" to 300,
                "perrserker" to 300,
                "varoom" to 300
            ),
            Rarity.RARE to mapOf(
                "skarmory" to 200,
                "steelix" to 200,
                "aggron" to 200,
                "bronzong" to 200,
                "klinklang" to 200,
                "aegislash" to 200,
                "klefki" to 200,
                "celesteela" to 200,
                "copperajah" to 200,
                "duraludon" to 200,
                "gholdengo" to 200,
                "orthworm" to 200,
                "revavroom" to 200
            ),
            Rarity.EPIC to mapOf(
                "jirachi" to 100,
                "metagross" to 100,
                "registeel" to 100,
                "arceus aspect=steel-plate" to 100,
                "dialga" to 100,
                "cobalion" to 100,
                "genesect aspect=water-drive" to 100,
                "genesect aspect=electric-drive" to 100,
                "genesect aspect=fire-drive" to 100,
                "genesect aspect=ice-drive" to 100,
                "magearna" to 100,
                "necrozma aspect=dusk-fusion" to 100,
                "silvally aspect=steel-memory" to 100,
                "melmetal" to 100,
                "meltan" to 100,
                "zacian aspect=crowned" to 100,
                "zamazenta aspect=crowned" to 100,
                "archaludon" to 100,
                "ironcrown" to 100
            ),
        )
    )
    private val waterCache = mapOf(
        "pools" to mapOf(
            Rarity.COMMON to mapOf(
                "horsea" to 400,
                "magikarp" to 400,
                "marill" to 400,
                "wooper" to 400,
                "barboach" to 400,
                "feebas" to 400,
                "lotad" to 400,
                "wingull" to 400,
                "mantyke" to 400,
                "basculin aspect=whitestriped" to 400,
                "tympole" to 400,
                "dewpider" to 400,
                "wishiwashi" to 400,
                "arrokuda" to 400,
                "chewtle" to 400,
                "wiglett" to 400
            ),
            Rarity.UNCOMMON to mapOf(
                "goldeen" to 300,
                "krabby" to 300,
                "poliwag" to 300,
                "poliwhirl" to 300,
                "psyduck" to 300,
                "seadra" to 300,
                "seel" to 300,
                "shellder" to 300,
                "slowpoke" to 300,
                "staryu" to 300,
                "tentacool" to 300,
                "azumarill" to 300,
                "chinchou" to 300,
                "corsola" to 300,
                "quagsire" to 300,
                "qwilfish" to 300,
                "remoraid" to 300,
                "carvanha" to 300,
                "castform aspect=rainy-form" to 300,
                "clamperl" to 300,
                "corphish" to 300,
                "lombre" to 300,
                "luvdisc" to 300,
                "pelipper" to 300,
                "wailmer" to 300,
                "buizel" to 300,
                "finneon" to 300,
                "shellos" to 300,
                "shellos aspect=east-sea" to 300,
                "dewott" to 300,
                "ducklett" to 300,
                "frillish" to 300,
                "oshawott" to 300,
                "palpitoad" to 300,
                "panpour" to 300,
                "tirtouga" to 300,
                "clauncher" to 300,
                "pyukumuku" to 300,
                "finizen" to 300,
                "wugtrio" to 300
            ),
            Rarity.RARE to mapOf(
                "squirtle" to 150,
                "totodile" to 150,
                "mudkip" to 150,
                "piplup" to 150,
                "oshawott aspect=region-bias-hisui" to 150,
                "froakie" to 150,
                "popplio" to 150,
                "sobble" to 150,
                "quaxly" to 300,
                "cloyster" to 200,
                "dewgong" to 200,
                "golduck" to 200,
                "gyarados" to 200,
                "kingler" to 200,
                "lapras" to 200,
                "poliwrath" to 200,
                "seaking" to 200,
                "slowbro" to 200,
                "starmie" to 200,
                "tentacruel" to 200,
                "vaporeon" to 200,
                "kingdra" to 200,
                "lanturn" to 200,
                "mantine" to 200,
                "octillery" to 200,
                "politoed" to 200,
                "slowking" to 200,
                "crawdaunt" to 200,
                "gorebyss" to 200,
                "huntail" to 200,
                "ludicolo" to 200,
                "milotic" to 200,
                "relicanth" to 200,
                "sharpedo" to 200,
                "wailord" to 200,
                "whiscash" to 200,
                "floatzel" to 200,
                "gastrodon" to 200,
                "lumineon" to 200,
                "rotom aspect=wash-appliance" to 200,
                "alomomola" to 200,
                "basculin" to 200,
                "basculin aspect=bluestriped" to 200,
                "carracosta" to 200,
                "jellicent" to 200,
                "seismitoad" to 200,
                "simipour" to 200,
                "swanna" to 200,
                "clawitzer" to 200,
                "araquanid" to 200,
                "bruxish" to 200,
                "arctovish" to 200,
                "barraskewda" to 200,
                "cramorant aspect=gulping-form" to 200,
                "cramorant aspect=gorging-form" to 200,
                "dracovish" to 200,
                "drednaw" to 200,
                "basculegion" to 200,
                "dondozo" to 200,
                "palafin" to 200,
                "tatsugiri aspect=tatsugiri-texture-droopy" to 200,
                "tatsugiri aspect=tatsugiri-texture-stretchy" to 200,
                "veluza" to 200
            ),
            Rarity.EPIC to mapOf(
                "suicune" to 100,
                "kyogre" to 100,
                "kyogre aspect=primal" to 100,
                "arceus aspect=water-plate" to 100,
                "manaphy" to 100,
                "palkia" to 100,
                "phione" to 100,
                "keldeo" to 100,
                "silvally aspect=water-memory" to 100,
                "tapufini" to 100,
                "wishiwashi aspect=school-form" to 100,
                "urshifu aspect=rapid_strike-style" to 100,
                "ogerpon aspect=wellspring-mask" to 100,
                "ogerpon aspect=embody-aspect aspect=wellspring-mask" to 100,
                "palafin aspect=hero-form" to 100,
                "walkingwake" to 100
            ),
        )
    )
}