/*
 * Copyright (c) 2026. gitoido-mc
 * This Source Code Form is subject to the terms of the GNU General Public License v3.0.
 * If a copy of the GNU General Public License v3.0 was not distributed with this file,
 * you can obtain one at https://github.com/gitoido-mc/rad-gyms/blob/main/LICENSE.
 */

package lol.gito.radgyms.fabric.datagen.provider.caches

import lol.gito.radgyms.common.CACHE_DEFAULT_ENTRY_WEIGHT_COMMON
import lol.gito.radgyms.common.CACHE_DEFAULT_ENTRY_WEIGHT_EPIC
import lol.gito.radgyms.common.CACHE_DEFAULT_ENTRY_WEIGHT_RARE
import lol.gito.radgyms.common.CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON
import lol.gito.radgyms.common.cache.CacheDTO
import net.minecraft.world.item.Rarity

val NORMAL_CACHE =
    CacheDTO(
        mapOf(
            Rarity.COMMON.serializedName.lowercase() to
                mapOf(
                    "azurill" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "bidoof" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "bunnelby" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "fletchling" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "happiny" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "hoothoot" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "igglybuff" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "jigglypuff" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "lechonk" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "lillipup" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "meowth" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "munchlax" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "patrat" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "pidgey" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "pidove" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "pikipek" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "rattata" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "sentret" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "skitty" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "skwovet" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "slakoth" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "smeargle" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "spearow" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "starly" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "taillow" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "whismur" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "wooloo" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "yungoos" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "zigzagoon" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "zoroark hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                    "zorua hisuian" to CACHE_DEFAULT_ENTRY_WEIGHT_COMMON,
                ),
            Rarity.UNCOMMON.serializedName.lowercase() to
                mapOf(
                    "aipom" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "audino" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "bibarel" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "buneary" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "castform" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "chatot" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "deerling season=spring" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "delcatty" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "diggersby" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "doduo" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "dunsparce" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "eevee" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "farfetchd" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "fearow" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "furret" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "glameow" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "gumshoos" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "herdier" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "kecleon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "lickitung" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "linoone" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "loudred" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "minccino" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "persian" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "pidgeotto" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "porygon" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "raticate" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "rufflet" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "spinda" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "squawkabilly" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "staravia" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "stufful" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "swablu" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "tandemaus" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "teddiursa" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "tranquill" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "trumbeak" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "vigoroth" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "watchog" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                    "wigglytuff" to CACHE_DEFAULT_ENTRY_WEIGHT_UNCOMMON,
                ),
            Rarity.RARE.serializedName.lowercase() to
                mapOf(
                    "ditto" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "ambipom" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "bewear" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "blissey" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "bouffalant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "braviary" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "chansey" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "cinccino" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "dodrio" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "drampa" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "dubwool" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "dudunsparce landsnake_form=three-segment" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "dudunsparce" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "exploud" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "farigiraf" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "furfrou" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "girafarig" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "greedent" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "indeedee female" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "kangaskhan" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "komala" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "lickilicky" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "lopunny" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "maushold maushold_family=four" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "maushold" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "miltank" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "noctowl" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "oinkologne female" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "oinkologne male" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "oranguru" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "pidgeot" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "porygon2" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "porygonz" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "purugly" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "sawsbuck season=spring" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "snorlax" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "stantler" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "staraptor" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "stoutland" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "swellow" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "tauros" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "toucannon" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "unfezant" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "ursaring" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "wyrdeer" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                    "zangoose" to CACHE_DEFAULT_ENTRY_WEIGHT_RARE,
                ),
            Rarity.EPIC.serializedName.lowercase() to
                mapOf(
                    "ursaluna bloodmoon" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "arceus" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "meloetta" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "regigigas" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "silvally" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "slaking" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "terapagos" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                    "typenull" to CACHE_DEFAULT_ENTRY_WEIGHT_EPIC,
                ),
        ),
    )
