#file: noinspection SpellCheckingInspection
name: Build and publish project artifacts on platforms
on:
  release:
    types:
      - published
  push:
    branches:
      - main
  workflow_dispatch:

env:
  project_slug: rad-gyms
  curseforge_id: 1196570
  modrinth_id: eF8kqlHd
  cobblemon: 1.8.1
  rctapi: 0.16.0-beta

jobs:
  build:
    name: "Build mod jars"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Current Java LTS
        ]
        loader: [
          fabric,
          neoforge,
          common,
        ]
    outputs:
      version: ${{ steps.version.outputs.MOD_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Build
        uses: burrunan/gradle-cache-action@v3
        with:
          read-only: true
          arguments: :x-${{ matrix.loader }}:build
      - name: Save version output
        id: version
        run: echo "MOD_VERSION=$(gradle currentVersion -q -Prelease.quiet)" >> "$GITHUB_OUTPUT"
      - name: Capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-${{ matrix.loader }}
          path: |
            x-${{ matrix.loader }}/build/libs/${{ env.project_slug }}-${{ matrix.loader }}-${{ steps.version.outputs.MOD_VERSION }}.jar
            x-${{ matrix.loader }}/build/libs/${{ env.project_slug }}-${{ matrix.loader }}-${{ steps.version.outputs.MOD_VERSION }}-sources.jar

  publish:
    if: github.event_name == 'release'
    name: "Publish artifacts on platforms"
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        loader: [
          fabric,
          neoforge,
        ]
    steps:
      - name: Retrieve build artifacts
        uses: actions/download-artifact@v8
      - name: Publish ${{ matrix.loader }} version (CurseForge/Modrinth)
        uses: Kira-NT/mc-publish@v3.3
        with:
          name: "Rad Gyms ${{ needs.build.outputs.version }} for Cobblemon ${{ env.cobblemon }}"
          java: 21
          game-versions: 1.21.1
          loaders: ${{ matrix.loader }}

          files: |
            x-${{ matrix.loader }}/build/libs/${{ env.project_slug }}-${{ matrix.loader }}-${{ needs.build.outputs.version }}.jar
            x-${{ matrix.loader }}/build/libs/${{ env.project_slug }}-${{ matrix.loader }}-${{ needs.build.outputs.version }}-sources.jar

          version: "${{ env.cobblemon }}_${{ needs.build.outputs.version }}"
          version-type: release
          environment: client | server

          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: ${{ env.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: ${{ env.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          dependencies: |
            architectury-api(required){curseforge:419699}{modrinth:lhGA9TYQ}
            cobblemon@${{ env.cobblemon }}(required){curseforge:687131}{modrinth:MdwFAVRL}
            radical-cobblemon-trainers-api@${{ env.rctapi }}(required){curseforge:1152792}{modrinth:CBfM2yw7}
